name: Publish

on: workflow_dispatch
    
    
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkg_root: [./Packages/ga.fuquna.syncutilformirror]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      with:
        dry_run: true
        working_directory: ${{ matrix.pkg_root }}  
        extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
