name: Release

on: 
  push:
    branches:
      - main,
  workflow_dispatch:    
    
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkg_root: [./Packages/ga.fuquna.syncutilformirror]

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v3
      with:
        semantic_version: 19
        branch: main
        working_directory: ${{ matrix.pkg_root }}  
        extra_plugins: |
            @semantic-release/changelog@6
            @semantic-release/git
        dry_run: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
